### ISSUE TITLE
Version 1.1.0 suggestion + problem

### ISSUE THREAD

**Issue by happysurf** [Baptistou/PopupFilter#1]
Great work on 1.1.0 version, the icon colors and the badge are great for improve the functionality.
In Confirm Mode the number of blocked popup is white on light yellow, this is hard to see, maybe is better change the color in black if possible.
Sometimes the blocked popups windows are open in background in taskbar, in this case the user don't have the control in real time.
In addition some legitimate links are not correctly recognized (undefined).
For example: 
- Open the site: http://www.filmpertutti.black/1-animali-fantastici-e-dove-trovarli-2016/
- In Confirm Mode go to below of second video and click on any of streaming links: 
Speedvideo
Wstream
FlashX
Nowvideo;
The links are not open if you click on > Display..
Thanks.

**Comment by Baptistou** [comment]
Hello, thank you for your comment. I tried the different links above and they were working properly in Confirm Mode with PopupFilter 1.2. Maybe this issue is solved with this next update which will be available for everyone shortly. If the issue persists, please send me some screenshots step by step.
Concerning the badge, I will change the color for the next version ;)
And for the background popups, maybe some users don't want to be disturbed when they are on a website. I am adding a new setting to decide if popups should be opened in front or in background in Confirm Mode.
