### ISSUE TITLE
[feature request] open popup window as tab

### ISSUE THREAD

**Issue by cubakcabak** [Baptistou/PopupFilter#2]
have an option to automatically open popup window as tab, preferably next to the parent tab.

**Comment by Baptistou** [comment]
Hi! Thank you for your comment and sorry for the delay.

I did some tests and unfortunately it is impossible to make [window.open](https://developer.mozilla.org/en-US/docs/Web/API/Window/open) to open a new tab instead of a new window through a WebExtension. The only possible thing is to merge windows after it was created. But the user is still annoyed by a window appearing, loading then closing in front of him, which looks like a buggy behavior.

However, a setting already exists in Firefox named [browser.link.open_newwindow.restriction](https://support.mozilla.org/en-US/questions/1066799). Is it what you are looking for?
